### ISSUE TITLE
Show cost data over time 

### ISSUE THREAD

**Issue by vsmart** [thegreenwebfoundation/green-cost-explorer#12]
As outlined in the [readme](https://github.com/thegreenwebfoundation/green-cost-explorer#usage), show cost data split over time using the API's given time series chunks: 

```
|          | Grey   | Green  |
-----------|--------|--------|
|Aug  2018 |  40%   |  60%   |
|Sept 2018 |  40%   |  60%   |
|Oct  2018 |  40%   |  60%   |
|Nov  2018 |  40%   |  60%   |
|Dec  2018 |  40%   |  60%   |

```

rather than only
```
|          | Grey   | Green  |
-----------|--------|--------|
|Total     |  40%   |  60%   |
```

Changes are needed in two places to do this: 

1) note timestamp when aggregating data by region [here](https://github.com/thegreenwebfoundation/green-cost-explorer/blob/master/src/index.js#L123-L127) 
2) respect timestamp when summing up total [here](https://github.com/thegreenwebfoundation/green-cost-explorer/blob/master/src/index.js#L82-L85) 

cc @mrchrisadams

**Comment by mrchrisadams** [comment]
Sounds good Franka 👍
